INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Jhon', 'courses/Java', 500,'2022-09-25');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Raul', 'courses/Java', 500,'2022-09-28');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Pedro', 'courses/Java', 500,'2022-10-05');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Orlando', 'courses/Java', 500,'2022-10-15');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Daniel', 'courses/Java', 500,'2022-10-25');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'Manuel', 'courses/Java', 500,'2022-10-26');
